### ISSUE TITLE
Crash after Work Order plays -- fence post error 

### ISSUE THREAD

**Issue by jameslkey** [jameslkey/CERM-Morse-Code-Exhibit#2]
Traceback (most recent call last):
  File "Morse.py", line 200, in <module>
    main()
  File "Morse.py", line 196, in main
    cerm.run()
  File "Morse.py", line 123, in run
    self.sendmessage(completemessage)
  File "Morse.py", line 152, in sendmessage
    display = trans.morsedecode(str(char))
  File "/CERMMorse/pyammorse/pyammorse.py", line 82, in morsedecode
    if stream[-1] != "\\":
IndexError: list index out of range

**Comment by jameslkey** [comment]
Fixed
